site_name: blog
site_description: Kratapps Blog 
site_author: Ondrej Kratochvil

# Theme configuration
theme:
  name: material
  custom_dir: overrides
  logo: images/logo_kratapps.svg
  favicon: images/favicon.ico
  palette:
    - scheme: default
      primary: white
      accent: custom
  font:
    text: Roboto
    code: Roboto Mono
  features:
    #  - index.pages
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    - navigation.path
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    #    - toc.integrate

# Plugins configuration
plugins:
  - search:
      separator: '[\s\u200b\-\.,!=\[\]()"`/]+'
  - minify:
      minify_html: true
  - blog:
      enabled: true
      blog_dir: .  # Directory where blog posts are located
      # You can add more configuration options for the blog plugin as needed
  - git-revision-date-localized
  - git-committers
    
# Markdown extensions
markdown_extensions:
  - toc
  - tables
  - fenced_code
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
    
# Extra
extra:
  generator: false
  social:
    - icon: fontawesome/regular/envelope
      link: mailto:hello@kratapps.com
    - icon: fontawesome/brands/github
      link: https://github.com/kratapps

# Extra CSS or JavaScript files
extra_css:
  - stylesheets/extra.css
  - stylesheets/hljs-kratapps.css
extra_javascript:
  - scripts/highlight.min.js
  - scripts/highlightConfig.js
  
# Navigation configuration
nav:
  - Blog: index.md

