site_name: Blog
site_description: Blog 
site_author: Ondrej Kratochvil

# Theme configuration
theme:
  name: material
  custom_dir: overrides
  logo: images/logo_kratapps.svg
  favicon: images/favicon.ico
  palette:
    - scheme: default
      primary: white
      accent: custom
  font:
    text: Roboto
    code: Roboto Mono

# Plugins configuration
plugins:
  - search:
      separator: '[\s\u200b\-\.,!=\[\]()"`/]+'
  - minify:
      minify_html: true
  - blog:
      enabled: true
      blog_dir: .  # Directory where blog posts are located
      # You can add more configuration options for the blog plugin as needed
  - git-revision-date-localized
  - git-committers

# Navigation configuration
nav:
  - Blog: index.md
    
extra:
  generator: false
  social:
    - icon: fontawesome/regular/envelope
      link: mailto:hello@kratapps.com
    - icon: fontawesome/brands/github
      link: https://github.com/kratapps

# Extra CSS or JavaScript files
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

# Markdown extensions
markdown_extensions:
  - toc
  - tables
  - fenced_code

# Extra configuration options can be added here
